### ISSUE TITLE
🛠️ [refactor] Exception Handling

### ISSUE THREAD

**Issue by binary-ho** [binary-ho/imhere-server#3]
# 🛠️ 리팩토링이 필요한 부분
현재 Exception을 다루는 방식이 너무 엉망이다.
개선이 필요하다
## 1. Custom Exception 구현
#23 
클라이언트에게 예외 발생 상황에 대한 더 자세한 정보 제공이 필요하다.
Custom Execption Enum을 만들어 발생할 수 있는 예외 상황들에 대한 Http Status, 자세한 Error Code와 ErrorMessage를 제공할 필요가 있다.

## 2. 패키지 분리
#24 
예외가 너무 많아지면서 지금의 패키지 구조로는 이해하기가 힘들다.
도메인 위주의 패키지 구성으로 변경

## 3. API 응답 방식 통일 
현재 통일되지 않은 방식으로 응답 객체를 직접 JSON화 시켜 내려주고 있다.
클라이언트에게 ResponseEntity를 활용해 통일된 방식으로 응답을 전달하고,
더 자세한 정보를 제공하기 위해 실패 상황에 대한 응답을 만든다.

Response Entity를 사용한 이유는 HttpStatus 때문이다.
클라이언트에서 응답을 받았을 때, 
즉시 status를 까보고 성공-실패 여부를 판단하길 바랬다.
기존처럼 단순 Dto를 내려주는 방식은 모든 API에 대해 통일된 방식으로 실패 성공 여부를 즉시 확인하는게 어려울 것 같았다.
ResponseEntity를 사용하면, 
응답 객체 JSON 표현에 status code가 섞이지 않아서
실패 성공 여부를 바로 확인할 수 있고, 응답 data도 깔끔하게 다룰 수 있어 보여 Response Entity로 응답을 통일하기로 결정했다.

물론 @ResponseStatus를 붙여주는 방법도 있겠지만,
추후 Controller Advice를 이용해 프로젝트에서 발생하는 예외들을 한번에 걸러
각 예외에 맞는 HttpStatus 코드와 커스텀 예외 코드를 적절하게 반환할 예정이었으므로,
성공 상황에서도 ResponseEntity로 통일하고 싶었다.

그리고 @ResponseStatus를 사용한 코드들을 봤는데,
지극히 개인적이지만 ResponseEntity를 통해 status와 body를 한번에 넣어주는게 좀 더 읽어내기 편했다.

## 4. 공통 ErrorResponse와 @ControllerAdvice 도입
컨트롤러에서 try-catch문을 제거한 다음
@ExceptionHandler와 @ControllerAdvice 도입해서 전역적으로 에러 처리
가독성을 크게 향상시키고,
에러를 한 곳에서 처리할 수 있으며,
컨트롤러의 반환값이 관계 없이, 
에러 메시지와 커스텀 에러 코드를 포함시킨 공통 ErrorResponse 객체를 반환해줄 수 있다.

# ☑ Refactoring TODO
## 다른 이슈에서 처리
- [x] 앱 커스텀 예외 구현, 예외별 에러코드와 메시지 구현 #22 
- [x] e.printStackTrace()과 같은 성능 저해 요소 제거, 로거에 기록하도록 변경 #22 
- [x] 패키지 구조 변경 #24 

## 이번 이슈에서 처리 (#3)
- [x] 모든 API의 응답 방식을 HttpResponse를 이용하여 Status Code를 전달하도록 변경 
- [x] 에러 리스폰스 객체 구현 
- [x] @ExceptionHandler와 @ControllerAdvice 도입 
- [x] 컨트롤러에서 발생하는 예외에 대해 try-catch 제거
