### ISSUE TITLE
🚀 [feature] 서비스 계층 테스트 코드 작성 🌟 

### ISSUE THREAD

**Issue by binary-ho** [binary-ho/imhere-server#35]
주요 서비스 메서드들에 대한 테스트 코드를 작성해보자.

테스트 코드를 작성하던 중 큰 이슈들 정리

1. 권한 테스트를 위한 Test Security Context 구현
2. RedisTemplate, JavaMailSender 추상화 + 의존성 역전 
3. TokenService의 SECTRET 값을 빈을 통해 주입 받도록 변경 
4. 테스트 코드 작성

# 1. 권한 테스트를 위한 Test Security Context 구현

테스트를 위해 어노테이션을 이용해 편리하게 Security Context에 유저를 직접 저장하는 기능을 구현했다.
그리고 기본적인 AtuhenticationHelper대한 테스트 코드를 작성했다.

[@WithSecurityContext를 이용해 커스텀 UserDetails SecurityContext Test 코드 작성하기](https://dwaejinho.tistory.com/entry/%EC%BB%A4%EC%8A%A4%ED%85%80-UserDetails-SecurityContext-Test-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0)

관련 이슈 : #8 

# 2. RedisTemplate, JavaMailSender 추상화 + 의존성 역전

이슈에 내용 자세히 정리 : #45 

현재 서비스 EmailSender는 JavaMailSender와 RedisTemplate의 의존성을 바로 주입받고 있다.
RedisTemplate는 출석 서비스에서도 바로 의존성을 주입 받아 사용중이다.

테스트를 작성하던 중, 불편함을 느껴, 두 객체에 대한 추상화의 필요성을 느꼈다.
불편한 점

1. JavaMailSender을 테스트하려면 SMTP 서버와 연결해야 하며, 제한이 있는데 실제로 이메일을 발송한다.
2. Stubbing 할 때 JavaMailSender가 중간에 사용하는 MimeMessage 등 또한 Stubbing 해줘야 하면서 Stubbing이 복잡해진다.
3. RedisTemplate을 테스트 하려면 테스트시 Redis 서버를 가동해야 한다. Stubbing하기도 어렵다.

단순히 테스트하기 불편하다는 점을 넘어 이런 구체적인 기술과의 강결합은 애초에 하지 말았어야 했다.
처음 부터 특정 기술을 직접 의존해 사용한다면 설계 단계에서 구체적인 기술에 국한된 설계를 유발한다.
이런 구현은 변경에 유연하지 못한 프로젝트를 만든다.
이에, 추상화를 진행했다.

# 3. TokenService의 SECTRET 값을 빈을 통해 주입 받도록 변경

이슈에 내용 자세히 정리 : #52

TokenService는 토큰을 만들 때 사용하는 SECRET 값을 @Value 어노테이션을 사용해 설정파일에서 주입 받아 사용받았다.

![image](https://github.com/binary-ho/imhere-server/assets/71186266/fe47d074-a24e-482e-9f5f-f93a650a79f8)

토큰 값의 내용을 해석하려면 시크릿 값이 필요한데, 이런 식으로 바로 사용하는 경우, 
테스트시 캡슐화를 깨지 않으면서 시크릿 값을 사용하기가 어려웠다.

꼭 위와 같이 구현하지 않더라도, private final 내부 상수로 선언했더라도 똑같이 불편했을 것이다.
Secret Holder를 인터페이스로 만들어 구현체를 빈으로 만들어서 관리하겠다

# ☑ Implement TODO

- [x] PrincipalDetailsService 테스트 코드 작성
- [x] RedisTemplate를 사용해 출석 번호와 인증 코드를 저장-조회하는 로직 추상화 + 의존성 역전 -> #45 
- [x] JavaMailSender를 사용하는 부분을 추상화 하고, 의존성 역전 -> #45 
- [x] 자바 코드로 Fake 객체를 구현해 영향을 미치는 부분에 대한 테스트 코드 작성 -> #45 
- [x] 테스트를 위핸 객체들의 Fixture 구현
- [x] 테스트에 쓰이는 객체들의 초기화를 간편하게 하기 위한 TestContainer를 구현과 적용
- [x] AttendanceService  테스트 코드 작성 -> #45 
- [x] AuthService 테스트 코드 작성 -> #45 
- [x] EnrollmentService  테스트 코드 작성
- [x] LectureService  테스트 코드 작성
- [x] T#52 Service의 SECTRET 값을 빈을 통해 주입 받도록 변경 #52
