### ISSUE TITLE
🛠️ [refactor] RedisTemplate, JavaMailSender 추상화 + 의존성 역전

### ISSUE THREAD

**Issue by binary-ho** [binary-ho/imhere-server#45]
# 🛠️ 리팩토링이 필요한 부분
현재 서비스 EmailSender는 JavaMailSender와 RedisTemplate의 의존성을 바로 주입받고 있다.
RedisTemplate는 출석 서비스에서도 바로 의존성을 주입 받아 사용중이다.

테스트를 작성하던 중, 불편함을 느껴, 두 객체에 대한 추상화의 필요성을 느꼈다.
불편한 점
1. JavaMailSender을 테스트하려면 SMTP 서버와 연결해야 하며, 제한이 있는데 실제로 이메일을 발송한다.
2. Stubbing 할 때 JavaMailSender가 중간에 사용하는 MimeMessage 등 또한 Stubbing 해줘야 하면서 Stubbing이 복잡해진다.
3. RedisTemplate을 테스트 하려면 테스트시 Redis 서버를 가동해야 한다. Stubbing하기도 어렵다.

단순히 테스트하기 불편하다는 점을 넘어 이런 구체적인 기술과의 강결합은 애초에 하지 말았어야 했다.
처음 부터 특정 기술을 직접 의존해 사용한다면 설계 단계에서 구체적인 기술에 국한된 설계를 유발한다.

구체적으로는 설계 단계에서 어떤 서비스 A에 JavaMailSneder를 바로 사용하지 않고, 
"메일을 보낸다"라는 책임을 갖는 인터페이스만을 만들어 사용했다면, 
구체적인 기술을 미리 정할 필요도, 자세히 알 필요도 없다.
이 과정을 뒤로 미루고 나중에 결정할 수도 있다.
더 자유롭게 설계할 수 있다.

뿐만 아니라 이러한 설계는 결합도가 높아 기술의 변화에 유연하게 대처하기 어렵다. (변경에 취약하다.)
다른 기술로 바뀌게 된다면 사용중인 서비스 자체의 많은 부분을 수정해야 할 수도 있다.
(실제로도 변경 전 MailSender는 JavaMailSender에서만 쓰이는 다양한 로직들이 섞여 있었다.)
그리고 가독성이 매우 나빴다.
변경 이후에는 MailSender라는 인터페이스를 통해 그저 "메일 보내기" 하나만을 호출하니, 어떤 역할을 하는 클래스인지 명확해졌다. 

그래서 이름도 책임에 맞게 EmailVerificationService로 바꿀 수 있었다.

두 객체를 각각 추상화한 다음 빈으로 관리해 의존성을 주입 받아 의존성을 역전하겠다.
이후, 영향을 미치는 곳들에 대한 테스트를 작성한 다음
나머지 테스트를 완성하겠다 -> #35

이런 추상화와 의존성 역전은 단순히 Testability를 높혀줄 뿐만 아니라,
결합도를 낮춰주고, 더 유연한 "객체지향적" 코드를 짤 수 있게 도와준다.

# 리팩토링 작업 브랜치
feature/abstract-redis-template
feature/abstract-mail-sender

# ☑ Refactoring TODO
- [x] RedisTemplate를 사용해 출석 번호와 인증 코드를 저장-조회하는 로직 추상화 + 의존성 역전 -> #48 
- [x] 구현한 AttendanceNumberRepository와 VerificationCodeRepository가 영향을 미치는 부분 테스트 코드 작성 -> #48 
- [x] JavaMailSender를 추상화 하고, 의존성 역전 -> #49
- [x] JavaMailSender의 인터페이스 EmailSender가 영향을 미치는 부분 테스트 코드 작성 -> #49
